apiVersion: hyperfoil.io/v1alpha1
kind: Horreum
metadata:
  name: example-horreum
spec:
  route: horreum.apps.mycloud.example.com
  keycloak:
    route: keycloak.apps.mycloud.example.com
  postgres:
    persistentVolumeClaim: horreum-postgres
  report:
    route: hyperfoil-report.apps.mycloud.example.com
    persistentVolumeClaim: hyperfoil-report
